# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

#
# YAML variable templates
#
job_defaults: &job_defaults
  working_directory: ~/redux-list
  docker:
    - image: circleci/node:lts

job_filter: &job_filter
  filters:
    branches:
      only:
        - master

#
# Run all jobs in sequence
#
workflows:
  version: 2
  npm_deploy:
    jobs:
      - setup:
          <<: *job_filter
      - test:
          <<: *job_filter
          requires:
            - setup
      - coverage:
          <<: *job_filter
          requires:
            - test
      - publish:
          <<: *job_filter
          requires:
            - coverage

#
# Define atomic jobs
#
jobs:
  setup:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: "redux-all-is-list: Install npm packages"
          command: "npm run setup"

      - run:
          name: "redux-all-is-list: Babel compile"
          command: "npm run build"

      - save_cache:
          paths:
            - node_modules
            - dist
            - src
            - .git
            - .babelrc
            - .eslintrc
            - .gitignore
            - .nycrc
            - .prettierrc
            - README.md
            - CHANGELOG.md
            - package-lock.json
            - package.json
          key: redux-all-is-list-{{ .Branch }}-{{ .Revision }}

  test:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
            - redux-all-is-list-{{ .Branch }}-{{ .Revision }}

      - run:
          name: "redux-all-is-list: Run linter"
          command: "npm run lint"

      - run:
          name: "redux-all-is-list: Run tests"
          command: "npm run test"

  coverage:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
            - redux-all-is-list-{{ .Branch }}-{{ .Revision }}

      - run:
          name: "redux-all-is-list: Publish test coverage to COVERALLS"
          command: "npm run coverage"

  publish:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
            - redux-all-is-list-{{ .Branch }}-{{ .Revision }}

      - run:
          name: "redux-all-is-list: Release to npm with semantic-release"
          command: "npx semantic-release"

